name: kwant-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - colorama=0.4.6
  - contourpy=1.3.3
  - cpython=3.11.14
  - cycler=0.12.1
  - exceptiongroup=1.3.1
  - fonttools=4.61.1
  - freetype=2.14.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=78.2
  - impi_rt=2021.17.0
  - iniconfig=2.3.0
  - kiwisolver=1.4.9
  - kwant=1.5.0
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnsl=2.0.1
  - libpng=1.6.54
  - libscotch=7.0.10
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - matplotlib-base=3.10.8
  - metis=5.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.1.1
  - mpmath=1.3.0
  - mumps-include=5.8.1
  - mumps-seq=5.8.1
  - munkres=1.1.4
  - narwhals=2.16.0
  - ncurses=6.5
  - openjpeg=2.5.4
  - openssl=3.6.1
  - pillow=12.1.0
  - pip=26.0
  - plotly=6.5.2
  - pluggy=1.6.0
  - pthread-stubs=0.4
  - pygments=2.19.2
  - pytest=9.0.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-mumps=0.0.4
  - python_abi=3.11
  - qhull=2020.2
  - qsymm=1.4.0
  - readline=8.3
  - scipy=1.17.0
  - setuptools=80.10.2
  - six=1.17.0
  - sympy=1.14.0
  - tinyarray=1.2.5
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - wheel=0.46.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - numpy==2.4.1
      - packaging==25.0
      - pyparsing==3.3.1
prefix: /home/tobyfeng/miniforge3/envs/kwant-env
